"""Closed M3 schema for human-approved document transformations.

The Stage-A schema in :mod:`canonical_curation` stays move/rename-only.  This
module represents irreversible transformations only when every generated byte
and every source-to-output mapping is present in the immutable effect.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Mapping, Optional, Tuple

from . import canonical_curation as stage_a
from .canonical_json import canonical_json_bytes, sha256_bytes


PLAN_SCHEMA = "mnemosyne-canonical-curation-plan-v2"
IRREVERSIBLE_CONSEQUENCE_KO = (
    "이 Plan이 성공하면 표시된 원본은 사라지며, irreversible cutoff 후에는 "
    "과거 원본으로 되돌릴 수 없습니다."
)
TRANSFORMATION_ACTIONS = (
    "split",
    "merge",
    "rewrite",
    "duplicate_consolidation",
    "navigation",
)
MAPPING_DISPOSITIONS = (
    "RETAINED",
    "REORGANIZED",
    "CONSOLIDATED",
    "EXACT_DUPLICATE_REMOVED",
    "SEMANTIC_DUPLICATE_REMOVED",
)

_MAX_OUTPUT_BYTES = 8 * 1024 * 1024


@dataclass(frozen=True)
class CompleteOutput:
    """One complete UTF-8 output whose exact bytes are approved by the user."""

    output_id: str
    output_path: str
    content: str
    content_sha256: str
    document_role: str

    def __post_init__(self) -> None:
        stage_a._require_identifier(self.output_id, "output id")
        stage_a._require_relative_path(self.output_path, "output path")
        stage_a._public_text(self.content, "complete output", maximum=_MAX_OUTPUT_BYTES)
        raw = self.content.encode("utf-8")
        if len(raw) > _MAX_OUTPUT_BYTES or sha256_bytes(raw) != self.content_sha256:
            raise stage_a.CanonicalCurationError(
                "complete output bytes or hash are invalid",
                reason_code="PLAN_INVALID",
            )
        if self.document_role not in stage_a.COMMON_SPINE_ROLES:
            raise stage_a.CanonicalCurationError(
                "complete output document role is invalid",
                reason_code="PLAN_INVALID",
            )

    @property
    def content_bytes(self) -> bytes:
        return self.content.encode("utf-8")

    @property
    def canonical_value(self) -> dict[str, object]:
        return {
            "content": self.content,
            "content_sha256": self.content_sha256,
            "document_role": self.document_role,
            "output_id": self.output_id,
            "output_path": self.output_path,
        }


@dataclass(frozen=True)
class SourceOutputMapping:
    """Human-reviewable declaration of where each source section is retained."""

    mapping_id: str
    source_observation_id: str
    source_sections: Tuple[str, ...]
    output_id: str
    output_sections: Tuple[str, ...]
    disposition: str

    def __post_init__(self) -> None:
        stage_a._require_identifier(self.mapping_id, "mapping id")
        stage_a._require_identifier(
            self.source_observation_id,
            "mapping source observation id",
        )
        stage_a._require_identifier(self.output_id, "mapping output id")
        stage_a._require_non_empty_text_tuple(self.source_sections, "source sections")
        stage_a._require_non_empty_text_tuple(self.output_sections, "output sections")
        for section in (*self.source_sections, *self.output_sections):
            stage_a._public_text(section, "mapping section", maximum=256)
        if self.disposition not in MAPPING_DISPOSITIONS:
            raise stage_a.CanonicalCurationError(
                "source mapping disposition is invalid",
                reason_code="PLAN_INVALID",
            )

    @property
    def canonical_value(self) -> dict[str, object]:
        return {
            "disposition": self.disposition,
            "mapping_id": self.mapping_id,
            "output_id": self.output_id,
            "output_sections": list(self.output_sections),
            "source_observation_id": self.source_observation_id,
            "source_sections": list(self.source_sections),
        }


@dataclass(frozen=True)
class DisappearingContent:
    """Explicitly disclosed source material absent from the retained output."""

    source_observation_id: str
    source_sections: Tuple[str, ...]
    reason: str
    classification: str

    def __post_init__(self) -> None:
        stage_a._require_identifier(
            self.source_observation_id,
            "disappearing content source observation id",
        )
        stage_a._require_non_empty_text_tuple(
            self.source_sections,
            "disappearing content sections",
        )
        for section in self.source_sections:
            stage_a._public_text(section, "disappearing content section", maximum=256)
        stage_a._public_text(self.reason, "disappearing content reason", maximum=1024)
        if self.classification not in {
            "EXACT_DUPLICATE",
            "SEMANTIC_DUPLICATE",
            "NAVIGATION_ONLY",
        }:
            raise stage_a.CanonicalCurationError(
                "disappearing content classification is invalid",
                reason_code="PLAN_INVALID",
            )

    @property
    def canonical_value(self) -> dict[str, object]:
        return {
            "classification": self.classification,
            "reason": self.reason,
            "source_observation_id": self.source_observation_id,
            "source_sections": list(self.source_sections),
        }


@dataclass(frozen=True)
class TransformationEffect:
    """One approval-ready irreversible transformation with complete outputs."""

    effect_id: str
    action: str
    input_observation_ids: Tuple[str, ...]
    outputs: Tuple[CompleteOutput, ...]
    source_output_mappings: Tuple[SourceOutputMapping, ...]
    disappearing_content: Tuple[DisappearingContent, ...]
    risk_codes: Tuple[str, ...]
    review_status: str = "REVIEW_REQUIRED"
    irreversible: bool = True
    dependency_effect_ids: Tuple[str, ...] = ()

    def __post_init__(self) -> None:
        stage_a._require_identifier(self.effect_id, "effect id")
        if self.action not in TRANSFORMATION_ACTIONS:
            raise stage_a.CanonicalCurationError(
                "effect action is not implemented",
                reason_code="EFFECT_NOT_IMPLEMENTED",
            )
        if (
            type(self.input_observation_ids) is not tuple
            or not self.input_observation_ids
            or len(self.input_observation_ids) != len(set(self.input_observation_ids))
        ):
            raise stage_a.CanonicalCurationError(
                "source mapping membership is invalid",
                reason_code="PLAN_INVALID",
            )
        for observation_id in self.input_observation_ids:
            stage_a._require_identifier(observation_id, "effect input observation id")
        if (
            type(self.outputs) is not tuple
            or not self.outputs
            or any(type(output) is not CompleteOutput for output in self.outputs)
        ):
            raise stage_a.CanonicalCurationError(
                "complete output is required",
                reason_code="PLAN_INVALID",
            )
        if (
            type(self.source_output_mappings) is not tuple
            or not self.source_output_mappings
            or any(
                type(mapping) is not SourceOutputMapping
                for mapping in self.source_output_mappings
            )
        ):
            raise stage_a.CanonicalCurationError(
                "source mapping is incomplete",
                reason_code="PLAN_INVALID",
            )
        if (
            type(self.disappearing_content) is not tuple
            or any(
                type(item) is not DisappearingContent
                for item in self.disappearing_content
            )
        ):
            raise stage_a.CanonicalCurationError(
                "disappearing content evidence is invalid",
                reason_code="PLAN_INVALID",
            )
        stage_a._require_non_empty_text_tuple(self.risk_codes, "effect risk codes")
        if (
            self.review_status != "REVIEW_REQUIRED"
            or self.irreversible is not True
            or type(self.dependency_effect_ids) is not tuple
        ):
            raise stage_a.CanonicalCurationError(
                "transformation review evidence is invalid",
                reason_code="PLAN_INVALID",
            )
        for dependency in self.dependency_effect_ids:
            stage_a._require_identifier(dependency, "effect dependency")

        output_ids = [output.output_id for output in self.outputs]
        output_paths = [output.output_path.casefold() for output in self.outputs]
        mapping_ids = [mapping.mapping_id for mapping in self.source_output_mappings]
        mapped_sources = {
            mapping.source_observation_id for mapping in self.source_output_mappings
        }
        mapped_outputs = {mapping.output_id for mapping in self.source_output_mappings}
        disappearing_sources = {
            item.source_observation_id for item in self.disappearing_content
        }
        input_observation_ids = set(self.input_observation_ids)
        if (
            len(output_ids) != len(set(output_ids))
            or len(output_paths) != len(set(output_paths))
            or len(mapping_ids) != len(set(mapping_ids))
            or mapped_sources != input_observation_ids
            or mapped_outputs != set(output_ids)
            or not disappearing_sources <= input_observation_ids
        ):
            raise stage_a.CanonicalCurationError(
                "source mapping is incomplete or ambiguous",
                reason_code="PLAN_INVALID",
            )

    @property
    def canonical_value(self) -> dict[str, object]:
        return {
            "action": self.action,
            "dependency_effect_ids": sorted(self.dependency_effect_ids),
            "disappearing_content": [
                item.canonical_value
                for item in sorted(
                    self.disappearing_content,
                    key=lambda value: (
                        value.source_observation_id,
                        value.source_sections,
                    ),
                )
            ],
            "effect_id": self.effect_id,
            "input_observation_ids": sorted(self.input_observation_ids),
            "irreversible": self.irreversible,
            "outputs": [
                output.canonical_value
                for output in sorted(self.outputs, key=lambda value: value.output_id)
            ],
            "review_status": self.review_status,
            "risk_codes": sorted(self.risk_codes),
            "source_output_mappings": [
                mapping.canonical_value
                for mapping in sorted(
                    self.source_output_mappings,
                    key=lambda value: value.mapping_id,
                )
            ],
        }


@dataclass(frozen=True)
class TransformationPlan:
    """Immutable M3 Plan whose outputs and destructive boundary are explicit."""

    primary_workstream_id: str
    captured_lifecycle: str
    project_home: str
    project_identity: Tuple[int, int, int, int]
    root_identity: Tuple[int, int, int, int]
    policy_sha256: str
    source_observations: Tuple[stage_a.SourceObservation, ...]
    effects: Tuple[TransformationEffect, ...]
    spine: Tuple[stage_a.SpineEntry, ...]
    findings: Tuple[stage_a.CurationFinding, ...]
    unchanged_paths: Tuple[str, ...]
    out_of_scope_paths: Tuple[str, ...]
    final_paths: Tuple[str, ...]
    coverage: Tuple[Tuple[str, object], ...]
    parent_plan_sha256: Optional[str] = None
    schema: str = PLAN_SCHEMA
    spec_sha256: str = stage_a.APPROVED_REQUIREMENTS_SHA256
    cutoff_required: bool = True
    irreversible_consequence: str = IRREVERSIBLE_CONSEQUENCE_KO

    def __post_init__(self) -> None:
        stage_a._require_identifier(self.primary_workstream_id, "primary Workstream id")
        if self.captured_lifecycle != "active":
            raise stage_a.CanonicalCurationError(
                "M3 Plan requires an active Workstream",
                reason_code="WORKSTREAM_FROZEN",
            )
        stage_a._require_relative_path(self.project_home, "project home")
        for identity in (self.project_identity, self.root_identity):
            if (
                type(identity) is not tuple
                or len(identity) != 4
                or any(type(value) is not int or value < 0 for value in identity)
            ):
                raise stage_a.CanonicalCurationError(
                    "filesystem identity is invalid",
                    reason_code="PLAN_INVALID",
                )
        stage_a._require_hash(self.policy_sha256, "policy hash")
        if self.parent_plan_sha256 is not None:
            stage_a._require_hash(self.parent_plan_sha256, "parent plan hash")
        if (
            self.schema != PLAN_SCHEMA
            or self.spec_sha256 != stage_a.APPROVED_REQUIREMENTS_SHA256
            or self.cutoff_required is not True
            or self.irreversible_consequence != IRREVERSIBLE_CONSEQUENCE_KO
        ):
            raise stage_a.CanonicalCurationError(
                "M3 Plan seal is invalid",
                reason_code="PLAN_INVALID",
            )
        for value, item_type, label in (
            (self.source_observations, stage_a.SourceObservation, "source observations"),
            (self.effects, TransformationEffect, "effects"),
            (self.spine, stage_a.SpineEntry, "spine"),
            (self.findings, stage_a.CurationFinding, "findings"),
        ):
            if type(value) is not tuple or any(type(item) is not item_type for item in value):
                raise stage_a.CanonicalCurationError(
                    "M3 Plan %s are invalid" % label,
                    reason_code="PLAN_INVALID",
                )
        for value in (
            self.unchanged_paths,
            self.out_of_scope_paths,
            self.final_paths,
            self.coverage,
        ):
            if type(value) is not tuple:
                raise stage_a.CanonicalCurationError(
                    "M3 Plan collections are invalid",
                    reason_code="PLAN_INVALID",
                )
        if not self.effects:
            raise stage_a.CanonicalCurationError(
                "M3 Plan requires at least one transformation effect",
                reason_code="PLAN_INVALID",
            )
        if tuple(entry.role for entry in self.spine) != stage_a.COMMON_SPINE_ROLES:
            raise stage_a.CanonicalCurationError(
                "common spine roles are incomplete",
                reason_code="PLAN_INVALID",
            )

        observation_ids = [value.observation_id for value in self.source_observations]
        observations = {value.observation_id: value for value in self.source_observations}
        effect_ids = [value.effect_id for value in self.effects]
        effects = {value.effect_id: value for value in self.effects}
        input_ids = [
            observation_id
            for effect in self.effects
            for observation_id in effect.input_observation_ids
        ]
        output_ids = [
            output.output_id for effect in self.effects for output in effect.outputs
        ]
        output_paths = [
            output.output_path for effect in self.effects for output in effect.outputs
        ]
        input_id_set = set(input_ids)
        output_path_keys = [path.casefold() for path in output_paths]
        source_paths = {
            observation_id: observations[observation_id].relative_path
            for observation_id in input_ids
            if observation_id in observations
        }
        if (
            len(observation_ids) != len(set(observation_ids))
            or len(effect_ids) != len(set(effect_ids))
            or len(input_ids) != len(set(input_ids))
            or len(output_ids) != len(set(output_ids))
            or len(output_path_keys) != len(set(output_path_keys))
            or input_id_set != set(observation_ids)
        ):
            raise stage_a.CanonicalCurationError(
                "M3 Plan source or output membership is invalid",
                reason_code="PLAN_INVALID",
            )
        for effect in self.effects:
            effect_input_ids = set(effect.input_observation_ids)
            if (
                any(item not in observations for item in effect_input_ids)
                or any(item not in effects for item in effect.dependency_effect_ids)
            ):
                raise stage_a.CanonicalCurationError(
                    "M3 effect is not bound to the Plan",
                    reason_code="PLAN_INVALID",
                )
            for output in effect.outputs:
                matching_sources = {
                    observation_id
                    for observation_id, path in source_paths.items()
                    if path.casefold() == output.output_path.casefold()
                }
                if matching_sources and not matching_sources <= effect_input_ids:
                    raise stage_a.CanonicalCurationError(
                        "M3 Plan path graph is unsupported",
                        reason_code="PLAN_PATH_GRAPH_UNSUPPORTED",
                    )

        for path in (
            *self.unchanged_paths,
            *self.out_of_scope_paths,
            *self.final_paths,
        ):
            stage_a._require_relative_path(path, "M3 Plan coverage path")
        expected_final_paths = {
            *self.unchanged_paths,
            *output_paths,
        }
        final_path_keys = [path.casefold() for path in self.final_paths]
        if (
            len(final_path_keys) != len(set(final_path_keys))
            or set(self.final_paths) != expected_final_paths
        ):
            raise stage_a.CanonicalCurationError(
                "M3 Plan final path set is incomplete",
                reason_code="PLAN_INVALID",
            )

    @property
    def source_observation_sha256(self) -> str:
        return sha256_bytes(
            canonical_json_bytes(
                [
                    value.canonical_value
                    for value in sorted(
                        self.source_observations,
                        key=lambda item: item.observation_id,
                    )
                ]
            )
        )

    @property
    def output_manifest_sha256(self) -> str:
        return sha256_bytes(
            canonical_json_bytes(
                [
                    output.canonical_value
                    for effect in sorted(self.effects, key=lambda item: item.effect_id)
                    for output in sorted(effect.outputs, key=lambda item: item.output_id)
                ]
            )
        )

    @property
    def canonical_value(self) -> dict[str, object]:
        return {
            "captured_lifecycle": self.captured_lifecycle,
            "coverage": dict(self.coverage),
            "cutoff_required": self.cutoff_required,
            "effects": [
                value.canonical_value
                for value in sorted(self.effects, key=lambda item: item.effect_id)
            ],
            "final_paths": sorted(self.final_paths),
            "findings": [
                value.canonical_value
                for value in sorted(self.findings, key=lambda item: item.finding_id)
            ],
            "irreversible_consequence": self.irreversible_consequence,
            "out_of_scope_paths": sorted(self.out_of_scope_paths),
            "output_manifest_sha256": self.output_manifest_sha256,
            "parent_plan_sha256": self.parent_plan_sha256,
            "policy_sha256": self.policy_sha256,
            "primary_workstream_id": self.primary_workstream_id,
            "project_home": self.project_home,
            "project_identity": list(self.project_identity),
            "root_identity": list(self.root_identity),
            "schema": self.schema,
            "source_observation_sha256": self.source_observation_sha256,
            "source_observations": [
                value.canonical_value
                for value in sorted(
                    self.source_observations,
                    key=lambda item: item.observation_id,
                )
            ],
            "spec_sha256": self.spec_sha256,
            "spine": [value.canonical_value for value in self.spine],
            "unchanged_paths": sorted(self.unchanged_paths),
        }

    @property
    def canonical_bytes(self) -> bytes:
        return canonical_json_bytes(self.canonical_value)

    @property
    def sha256(self) -> str:
        return sha256_bytes(self.canonical_bytes)

    def subset(self, selected_effect_ids: Tuple[str, ...]) -> "TransformationPlan":
        if type(selected_effect_ids) is not tuple or not selected_effect_ids:
            raise stage_a.CanonicalCurationError(
                "selected effect membership is empty",
                reason_code="DECISION_INVALID",
            )
        by_id = {effect.effect_id: effect for effect in self.effects}
        selected = set(selected_effect_ids)
        if len(selected) != len(selected_effect_ids) or not selected <= set(by_id):
            raise stage_a.CanonicalCurationError(
                "selected effect membership is invalid",
                reason_code="DECISION_INVALID",
            )
        pending = list(selected)
        while pending:
            effect = by_id[pending.pop()]
            for dependency in effect.dependency_effect_ids:
                if dependency not in selected:
                    selected.add(dependency)
                    pending.append(dependency)
        effects = tuple(effect for effect in self.effects if effect.effect_id in selected)
        observation_ids = {
            observation_id
            for effect in effects
            for observation_id in effect.input_observation_ids
        }
        observations = tuple(
            observation
            for observation in self.source_observations
            if observation.observation_id in observation_ids
        )
        unselected_sources = tuple(
            observation.relative_path
            for observation in self.source_observations
            if observation.observation_id not in observation_ids
        )
        output_paths = tuple(
            output.output_path for effect in effects for output in effect.outputs
        )
        unchanged = tuple(sorted(set(self.unchanged_paths + unselected_sources)))
        coverage = dict(self.coverage)
        coverage.update(
            {
                "parent_effect_count": len(self.effects),
                "subset_effect_count": len(effects),
                "subset_source_count": len(observations),
            }
        )
        return replace(
            self,
            source_observations=observations,
            effects=effects,
            findings=tuple(
                finding
                for finding in self.findings
                if finding.relative_path
                in {observation.relative_path for observation in observations}
            ),
            unchanged_paths=unchanged,
            final_paths=tuple(sorted(set(unchanged + output_paths))),
            coverage=tuple(sorted(coverage.items())),
            parent_plan_sha256=self.sha256,
        )


@dataclass(frozen=True)
class TransformationDecision:
    action: str
    displayed_plan_sha256: str
    approved_plan: Optional[TransformationPlan]
    selected_effect_ids: Tuple[str, ...]
    review_package_hashes: Tuple[Tuple[str, str], ...]
    irreversible_acknowledgement: Optional[str]
    reason: Optional[str]

    def __post_init__(self) -> None:
        if self.action not in stage_a.DECISION_ACTIONS:
            raise stage_a.CanonicalCurationError(
                "decision action is invalid",
                reason_code="DECISION_INVALID",
            )
        stage_a._require_hash(self.displayed_plan_sha256, "displayed plan hash")
        if type(self.selected_effect_ids) is not tuple:
            raise stage_a.CanonicalCurationError(
                "decision membership is invalid",
                reason_code="DECISION_INVALID",
            )
        approving = self.action in {"APPROVE_ALL", "APPROVE_SELECTED"}
        if approving:
            if (
                type(self.approved_plan) is not TransformationPlan
                or not self.selected_effect_ids
                or self.irreversible_acknowledgement != IRREVERSIBLE_CONSEQUENCE_KO
            ):
                raise stage_a.CanonicalCurationError(
                    "irreversible acknowledgement is missing or invalid",
                    reason_code="DECISION_INVALID",
                )
        elif (
            self.approved_plan is not None
            or self.selected_effect_ids
            or self.irreversible_acknowledgement is not None
        ):
            raise stage_a.CanonicalCurationError(
                "non-approval decision cannot carry effects or acknowledgement",
                reason_code="DECISION_INVALID",
            )
        if self.approved_plan is not None:
            membership = tuple(effect.effect_id for effect in self.approved_plan.effects)
            if membership != self.selected_effect_ids:
                raise stage_a.CanonicalCurationError(
                    "approval effect membership differs from approved Plan",
                    reason_code="DECISION_INVALID",
                )
            bound = (
                self.approved_plan.sha256 == self.displayed_plan_sha256
                if self.action == "APPROVE_ALL"
                else self.approved_plan.parent_plan_sha256
                == self.displayed_plan_sha256
            )
            if not bound:
                raise stage_a.CanonicalCurationError(
                    "approved Plan is not bound to the displayed Plan",
                    reason_code="DECISION_INVALID",
                )
        expected_hash_names = {
            "html_sha256",
            "markdown_sha256",
            "meta_sha256",
            "semantic_sha256",
        }
        if (
            type(self.review_package_hashes) is not tuple
            or {name for name, _value in self.review_package_hashes}
            != expected_hash_names
        ):
            raise stage_a.CanonicalCurationError(
                "review package binding is incomplete",
                reason_code="DECISION_INVALID",
            )
        for _name, value in self.review_package_hashes:
            stage_a._require_hash(value, "review package hash")
        if self.reason is not None:
            stage_a._public_text(self.reason, "decision reason", maximum=1024)

    @property
    def canonical_value(self) -> dict[str, object]:
        return {
            "action": self.action,
            "approved_plan_sha256": (
                None if self.approved_plan is None else self.approved_plan.sha256
            ),
            "displayed_plan_sha256": self.displayed_plan_sha256,
            "irreversible_acknowledgement": self.irreversible_acknowledgement,
            "output_manifest_sha256": (
                None
                if self.approved_plan is None
                else self.approved_plan.output_manifest_sha256
            ),
            "reason": self.reason,
            "review_package_hashes": dict(self.review_package_hashes),
            "selected_effect_ids": list(self.selected_effect_ids),
            "source_observation_sha256": (
                None
                if self.approved_plan is None
                else self.approved_plan.source_observation_sha256
            ),
        }

    @property
    def sha256(self) -> str:
        return sha256_bytes(canonical_json_bytes(self.canonical_value))


def compile_decision(
    plan: TransformationPlan,
    *,
    action: str,
    review_package_hashes: Mapping[str, str],
    selected_effect_ids: Tuple[str, ...] = (),
    irreversible_acknowledgement: Optional[str] = None,
    reason: Optional[str] = None,
) -> TransformationDecision:
    """Bind one exact M3 choice and acknowledgement to an immutable Plan."""

    if type(plan) is not TransformationPlan or action not in stage_a.DECISION_ACTIONS:
        raise stage_a.CanonicalCurationError(
            "decision input is invalid",
            reason_code="DECISION_INVALID",
        )
    if action in {"APPROVE_ALL", "APPROVE_SELECTED"} and plan.findings:
        raise stage_a.CanonicalCurationError(
            "Plan has unresolved conflict findings",
            reason_code="REVIEW_NOT_READY",
        )
    hashes = dict(review_package_hashes)
    if action == "APPROVE_ALL":
        if selected_effect_ids:
            raise stage_a.CanonicalCurationError(
                "full approval cannot override effect membership",
                reason_code="DECISION_INVALID",
            )
        approved = plan
        membership = tuple(effect.effect_id for effect in plan.effects)
    elif action == "APPROVE_SELECTED":
        approved = plan.subset(selected_effect_ids)
        membership = tuple(effect.effect_id for effect in approved.effects)
    else:
        approved = None
        membership = ()
    return TransformationDecision(
        action=action,
        displayed_plan_sha256=plan.sha256,
        approved_plan=approved,
        selected_effect_ids=membership,
        review_package_hashes=tuple(sorted(hashes.items())),
        irreversible_acknowledgement=irreversible_acknowledgement,
        reason=reason,
    )


__all__ = [
    "CompleteOutput",
    "DisappearingContent",
    "IRREVERSIBLE_CONSEQUENCE_KO",
    "MAPPING_DISPOSITIONS",
    "PLAN_SCHEMA",
    "SourceOutputMapping",
    "TRANSFORMATION_ACTIONS",
    "TransformationDecision",
    "TransformationEffect",
    "TransformationPlan",
    "compile_decision",
]
